apiVersion: v1
kind: Service
metadata:
  name: budget-ai-svc
  namespace: dev
  labels:
    app: budget-ai-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: budget-ai-app
