apiVersion: v1
kind: Service
metadata:
  name: budget-api-svc
  namespace: dev
  labels:
    app: budget-api-app
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: budget-api-app
