apiVersion: v1
kind: Service
metadata:
  name: budget-web-svc
  namespace: dev
  labels:
    app: budget-web-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: budget-web-app
