apiVersion: v1
kind: ConfigMap
metadata:
  name: budget-ai-dev-config
  namespace: dev
data:
  NEXTAUTH_URL: https://budget-dev.vandenit.be
  AUTH0_BASE_URL: https://budget-dev.vandenit.be
  AUTH0_ISSUER_BASE_URL: "https://vandenit.eu.auth0.com"
  AUTH0_SCOPE: "openid profile"
  AUTH0_CALLBACK: api/defauth/callback
  AUTH0_AUDIENCE: "https://vandenit.eu.auth0.com/api/v2/"
  API_URL: "http://budget-api-svc.dev:4000"
