name: Deploy to Digital Ocean Kubernetes.

on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: filipvdb321/vandenit-tina:${{ github.sha }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Replace image tag in Kubernetes deployment file
        run: |
          envsubst '$IMAGE_TAG' < ./kube/dev/deployment.yml.template > ./kube/dev/deployment.yml

      - name: Save Digital Ocean kubeconfig
        run: doctl kubernetes cluster kubeconfig save k8s-1-vandenit-ams3-dev

      - name: Deploy config to Kubernetes
        run: |
          kubectl apply -f ./kube/config/dev

      - name: Create/Update Kubernetes secrets
        run: |
          kubectl create secret generic vandenit-tina-secrets \
            --namespace=dev \
            --from-literal=POSTMARK_API_TOKEN='${{ secrets.POSTMARK_API_TOKEN }}' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./kube/dev/deployment.yml
          kubectl apply -f ./kube/dev/service.yml

      - name: Verify deployment
        run: kubectl rollout status deployment/vandenit-tina -n dev
